//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibertyUpdater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibertyUpdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] segoeui {
            get {
                object obj = ResourceManager.GetObject("segoeui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] segoeuib {
            get {
                object obj = ResourceManager.GetObject("segoeuib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] segoeuii {
            get {
                object obj = ResourceManager.GetObject("segoeuii", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] segoeuil {
            get {
                object obj = ResourceManager.GetObject("segoeuil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SegoeUIMono_Bold {
            get {
                object obj = ResourceManager.GetObject("SegoeUIMono_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SegoeUIMono_Regular {
            get {
                object obj = ResourceManager.GetObject("SegoeUIMono_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] segoeuiz {
            get {
                object obj = ResourceManager.GetObject("segoeuiz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SegoeWP {
            get {
                object obj = ResourceManager.GetObject("SegoeWP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SegoeWP_Black {
            get {
                object obj = ResourceManager.GetObject("SegoeWP_Black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SegoeWP_Bold {
            get {
                object obj = ResourceManager.GetObject("SegoeWP_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SegoeWP_Light {
            get {
                object obj = ResourceManager.GetObject("SegoeWP_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SegoeWP_Semibold {
            get {
                object obj = ResourceManager.GetObject("SegoeWP_Semibold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SegoeWP_Semilight {
            get {
                object obj = ResourceManager.GetObject("SegoeWP_Semilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] seguisb {
            get {
                object obj = ResourceManager.GetObject("seguisb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] seguisym {
            get {
                object obj = ResourceManager.GetObject("seguisym", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Semilight {
            get {
                object obj = ResourceManager.GetObject("Semilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
