//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liberty.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Liberty.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] KV {
            get {
                object obj = ResourceManager.GetObject("KV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [m10]
        ///0x83CC1C79 = Elite
        ///0x880C201D = Noble 6
        ///0x8BE7234F = Jorge
        ///0x8CAC240B = Kat
        ///0x914928A8 = Civilian Male
        ///0x924829A7 = Civilian Female
        ///0x925A29B9 = Moa
        ///0x96C92DBD = Spartan AI
        ///0x979B2E6A = Spartan Hologram
        ///0xF502102B = Grunt
        ///0xF782120A = Jackal
        ///0xF84312AB = Jackal Hologram
        ///0xF85112B6 = Marine Male
        ///
        ///[m20]
        ///0x85001D2D = Elite
        ///0x888A2017 = Grunt
        ///0x89FC2176 = Jackal
        ///0x8A8821E7 = Jackal Hologram
        ///0x8AC62222 = Hunter
        ///0x8BC3230C = Spartan AI
        ///0x8F972636 = Jorge
        ///0x905C26F2 = Kat
        ///0x950F2BA5 = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string taglist {
            get {
                return ResourceManager.GetString("taglist", resourceCulture);
            }
        }
        
        internal static byte[] Updater {
            get {
                object obj = ResourceManager.GetObject("Updater", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
